"""
update taskflows

Revision ID: 9144da6fa512
Revises: 0433f286fcf8
Create Date: 2025-05-01 17:28:42.305554
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9144da6fa512'
down_revision: Union[str, None] = '0433f286fcf8'
branch_labels: Union[str, Sequence[str], None] = 'None'
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taskflows_description'), 'taskflows', ['description'], unique=False)
    op.create_index(op.f('ix_taskflows_id'), 'taskflows', ['id'], unique=False)
    op.create_index(op.f('ix_taskflows_title'), 'taskflows', ['title'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskflows_title'), table_name='taskflows')
    op.drop_index(op.f('ix_taskflows_id'), table_name='taskflows')
    op.drop_index(op.f('ix_taskflows_description'), table_name='taskflows')
    op.drop_table('taskflows')
    # ### end Alembic commands ###