"""
completed_field

Revision ID: 9421c1dd087d
Revises: 9144da6fa512
Create Date: 2025-05-01 17:31:05.104588
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9421c1dd087d'
down_revision: Union[str, None] = '9144da6fa512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taskflows', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taskflows', 'completed')
    # ### end Alembic commands ###